version: "3.7"

services:
  app:
    container_name: app
    build: .
    ports:
      - 3333:3333
    networks:
      - network
    env_file:
      - .env
    volumes:
      - app:/usr/src/app/data

  facile_chellenge_db:
    image: postgres:13
    container_name: facile_challenge_postgres
    restart: always
    hostname: hpostgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/facile_challenge-db/
    volumes:
      - postgres:/usr/src/app/data
    networks:
      - network

volumes:
  postgres:
    name: facile_challenge-db
  app:
    name: facile_challenge-app

networks:
  network:
    name: kapay-network
